/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : iCal
 #	author : miyako
 #	2014/02/10
 #
 # --------------------------------------------------------------------------------*/

#import "helper.h"
#import "listener.h"

#import "ical_event.h"
#import "ical_task.h"
#import "ical_calendar.h"
#import "ical_calendar_store.h"
#import "ical_tools.h"
#import "ical_alarm.h"
#import "ical_application.h"

// --- Notification
void iCal_Set_notification_method(sLONG_PTR *pResult, PackagePtr pParams);
void iCal_Get_notification_method(sLONG_PTR *pResult, PackagePtr pParams);

#import "ical_timezome.h"
