/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : iCal
 #	author : miyako
 #	2013/09/20
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

// --- Notification
void iCal_Set_notification_method(sLONG_PTR *pResult, PackagePtr pParams);
void iCal_Get_notification_method(sLONG_PTR *pResult, PackagePtr pParams);

void listenerLoopExecuteMethodByID();
void listenerLoopFinish();
void listenerLoop();